// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBiT7jJTT92OTIStAVFMUrz0R7BLM_qiY',
    appId: '1:258120052562:web:b5731849995fddb7e2948b',
    messagingSenderId: '258120052562',
    projectId: 'after-hours-87c70',
    authDomain: 'after-hours-87c70.firebaseapp.com',
    storageBucket: 'after-hours-87c70.firebasestorage.app',
    measurementId: 'G-JB055QBRR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyxNQF7hruA9toXrgxbGM6TvCXvb10IJQ',
    appId: '1:258120052562:android:5c28ce1e0be6f449e2948b',
    messagingSenderId: '258120052562',
    projectId: 'after-hours-87c70',
    storageBucket: 'after-hours-87c70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY59LxQqXgbAUbCrNZgymQ_T0Y_lQoqHk',
    appId: '1:258120052562:ios:94aae9b2d9c457b0e2948b',
    messagingSenderId: '258120052562',
    projectId: 'after-hours-87c70',
    storageBucket: 'after-hours-87c70.firebasestorage.app',
    iosBundleId: 'com.example.afterHours',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY59LxQqXgbAUbCrNZgymQ_T0Y_lQoqHk',
    appId: '1:258120052562:ios:94aae9b2d9c457b0e2948b',
    messagingSenderId: '258120052562',
    projectId: 'after-hours-87c70',
    storageBucket: 'after-hours-87c70.firebasestorage.app',
    iosBundleId: 'com.example.afterHours',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBiT7jJTT92OTIStAVFMUrz0R7BLM_qiY',
    appId: '1:258120052562:web:77768adcbfa6c302e2948b',
    messagingSenderId: '258120052562',
    projectId: 'after-hours-87c70',
    authDomain: 'after-hours-87c70.firebaseapp.com',
    storageBucket: 'after-hours-87c70.firebasestorage.app',
    measurementId: 'G-HTG1E0FGJ9',
  );
}
